name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
projects: ["Project-Ticketing"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the issue you encountered
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: transaction-id
    attributes:
      label: Transaction ID
      description: Please provide the transaction ID related to this issue
      placeholder: Enter the transaction ID
    validations:
      required: true

  - type: dropdown
    id: transaction-type
    attributes:
      label: Type of Transaction
      description: Select the type of transaction related to this issue
      options:
        - Material
        - Produk
        - Lain-lain
    validations:
      required: true